# Generated by Django 2.1 on 2018-08-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='date published'),
        ),
    ]
