# Generated by Django 2.1 on 2018-08-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_messages', '0002_auto_20180829_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
