# Generated by Django 2.1 on 2018-08-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_messages', '0003_auto_20180829_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
