# Generated by Django 2.1 on 2018-09-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_messages', '0007_auto_20180904_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description '),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Price '),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title '),
        ),
    ]
