# Generated by Django 2.1 on 2018-09-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_messages', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
