# Generated by Django 2.1 on 2019-06-23 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_messages', '0012_auto_20190623_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritead',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
