# Generated by Django 2.1 on 2019-06-23 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_messages', '0013_auto_20190623_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritead',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='ad_messages.Ad'),
        ),
    ]
